Cookbook/Controllers/RecipeController.cs
using Cookbook.Areas.Identity.Data;
using Cookbook.Data;
using Cookbook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading;
using System.Threading.Tasks;

namespace Cookbook.Controllers
{

    public class RecipeController : Controller
    {
        private readonly ApplicationDbContext _db;
        private IWebHostEnvironment _environment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<RecipeController> _logger;

        public RecipeController(ApplicationDbContext db, IWebHostEnvironment environment, UserManager<ApplicationUser> userManager, ILogger<RecipeController> logger)
        {
            _db = db;
            _environment = environment;
            _userManager = userManager;
            _logger = logger;
        }

        // Page for search results
        public async Task<IActionResult> Index(string sortOrder, string sortBy, string currentFilter, string searchString, int? pageNumber, FilterBy? filterBy)
        {
            // sort search results by rating or date
            // toggle asc, desc by using the same sortBy twice
            if (sortBy == "rating")
            {
                if (sortOrder == "rating_desc")
                {
                    sortOrder = "rating_asc";
                } else
                {
                    sortOrder = "rating_desc";
                }
            } else if (sortBy == "date")
            {
                if (sortOrder == "date_desc")
                {
                    sortOrder = "date_asc";
                } else
                {
                    sortOrder = "date_desc";
                }
            }

            // sort by rating desc if nothing selected
            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "rating_desc";
            }

            ViewData["CurrentSort"] = sortOrder;
            ViewData["FilterBy"] = filterBy;

            // If the search string was changed, page has to be reset to 1
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            IQueryable<Recipe> recipes = _db.Recipe.AsNoTracking();

            // Filter results by search query
            if (!string.IsNullOrEmpty(searchString))
            {
                switch (filterBy)
                {
                    // get all recipes of creator
                    case FilterBy.UserName:
                        recipes = recipes.Where(x => x.Creator == searchString);
                        break;
                    // get all recipes with tag
                    case FilterBy.Tag:
                        List<int> tags2 = _db.Tag.AsNoTracking().Where(x => x.Title.Contains(searchString)).Select(x => x.Id).ToList();
                        List<int> recipeids2 = _db.RecipeTag.AsNoTracking().Where(x => tags2.Contains(x.TagId)).Select(x => x.RecipeId).ToList();
                        recipes = recipes.Where(x => recipeids2.Contains(x.Id));
                        break;
                    // get all recipes containing the search query in its ingredients, title or tags
                    default:
                        List<int> tags = _db.Tag.AsNoTracking().Where(x => x.Title.Contains(searchString)).Select(x => x.Id).ToList();
                        List<int> recipeids = _db.RecipeTag.AsNoTracking().Where(x => tags.Contains(x.TagId)).Select(x => x.RecipeId).ToList();
                        recipes = recipes.Where(x => x.Title.Contains(searchString) || x.Ingredients.Contains(searchString) || recipeids.Contains(x.Id));
                        break;
                }
            }

            // do the actual sorting
            switch (sortOrder)
            {
                case "date_asc":
                    recipes = recipes.OrderBy(x => x.CreationDate);
                    break;
                case "date_desc":
                    recipes = recipes.OrderByDescending(x => x.CreationDate);
                    break;
                case "rating_asc":
                    recipes = recipes.OrderBy(x => (x.OneStars + 2 * x.TwoStars + 3 * x.ThreeStars + 4 * x.FourStars + 5 * x.FiveStars) / ((x.OneStars + x.TwoStars + x.ThreeStars + x.FourStars + x.FiveStars) == 0 ? 1f : (x.OneStars + x.TwoStars + x.ThreeStars + x.FourStars + x.FiveStars)));
                    break;
                default:
                    recipes = recipes.OrderByDescending(x => (x.OneStars + 2 * x.TwoStars + 3 * x.ThreeStars + 4 * x.FourStars + 5 * x.FiveStars) / ((x.OneStars + x.TwoStars + x.ThreeStars + x.FourStars + x.FiveStars) == 0 ? 1f : (x.OneStars + x.TwoStars + x.ThreeStars + x.FourStars + x.FiveStars)));
                    break;
            }

            // get all recipes that will be displayed on this page
            int pageSize = 20;
            PaginatedList<Recipe> recipeList = await PaginatedList<Recipe>.CreateAsync(recipes.AsNoTracking(), pageNumber ?? 1, pageSize);
            List<string> imageFiles = new List<string>();
            List<string>[] recipeTags = new List<string>[recipeList.Count];

            // get thumbnails and tags of recipes on this page
            for (int i = 0; i < recipeList.Count; i++)
            {
                var image = _db.Image.AsNoTracking().Where(x => x.RecipeId == recipeList[i].Id).FirstOrDefault();
                imageFiles.Add(image == null? "" : image.FileName);

                recipeTags[i] = GetTagsOfRecipe(recipeList[i].Id);
            }

            ViewData["Images"] = imageFiles;
            ViewData["Tags"] = recipeTags;

            return View(recipeList);
        }

        // Redirects to List page showing recipes with given tag
        public IActionResult GetRecipesWithTag(string tag)
        {

            return RedirectToAction("Index", new { searchString = tag, filterBy = FilterBy.Tag });
        }

        // Redirects to List page showing recipes with given creator
        public IActionResult GetRecipesFromCreator(string creator)
        {
            return RedirectToAction("Index", new { searchString = creator, filterBy = FilterBy.UserName });
        }

        [Authorize]
        // Personal cookbook page. Contains recipes uploaded by user and saved recipes.
        public async Task<IActionResult> Cookbook(string sortOrder, string sortBy, string currentFilter, string searchString, int? pageNumber, string filterBy)
        {
            // decide sortorder
            // toggle asc, desc by using the same sortBy twice
            if (sortBy == "rating")
            {
                if (sortOrder == "rating_desc")
                {
                    sortOrder = "rating_asc";
                }
                else
                {
                    sortOrder = "rating_desc";
                }
            }
            else if (sortBy == "date")
            {
                if (sortOrder == "date_desc")
                {
                    sortOrder = "date_asc";
                }
                else
                {
                    sortOrder = "date_desc";
                }
            }

            // sort by rating desc if nothing selected
            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "rating_desc";
            }

            ViewData["CurrentSort"] = sortOrder;
            ViewData["FilterBy"] = filterBy;

            // If the search string was changed, page has to be reset to 1
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            IQueryable<Recipe> recipes = null;

            // filter recipes by categories
            switch (filterBy)
            {
                case "saved":
                    var saved = _db.SavedRecipe.AsNoTracking().Where(x => x.UserName == User.Identity.Name).Select(x => x.RecipeId);
                    recipes = _db.Recipe.AsNoTracking().Where(x => saved.Contains(x.Id));
                    break;
                case "created":
                    recipes = _db.Recipe.AsNoTracking().Where(x => x.Creator == User.Identity.Name);
                    break;
                // all recipes
                default:
                    var save = _db.SavedRecipe.AsNoTracking().Where(x => x.UserName == User.Identity.Name).Select(x => x.RecipeId);
                    recipes = _db.Recipe.AsNoTracking().Where(x => save.Contains(x.Id) || x.Creator == User.Identity.Name);
                    break;
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                // filter by searchstring
                var tags = _db.Tag.AsNoTracking().Where(x => x.Title.Contains(searchString)).Select(x => x.Id);
                var recipeids = _db.RecipeTag.AsNoTracking().Where(x => tags.Contains(x.TagId)).Select(x => x.RecipeId);
                recipes = recipes.AsNoTracking().Where(x => x.Title.Contains(searchString) || x.Ingredients.Contains(searchString) || recipeids.Contains(x.Id));
            }

            // do the actual sorting
            switch (sortOrder)
            {
                case "date_asc":
                    recipes = recipes.OrderBy(x => x.CreationDate);
                    break;
                case "date_desc":
                    recipes = recipes.OrderByDescending(x => x.CreationDate);

Cookbook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
    <script src="~/lib/font-awesome/js/all.js"></script>
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow pt-2 pb-1">
            <div class="container">
                <div class="row">
                    <a class="navbar-brand col-2 mr-4" asp-area="" asp-controller="Home" asp-action="Index">
                        <img class="w-100" src="~/images/CookbookLogo.png" alt="Logo" />
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-around col-9">
                        <form class="input-group mr-4" asp-controller="Recipe" asp-action="Index">
                            <input class="form-control my-0 py-1 font-18" name="searchString" type="text" placeholder="e.g. casserole, pork, dinner..." aria-label="Search">
                            <div class="input-group-append">
                                <button type="submit" class="input-group-text btn-main">
                                    <i class="fas fa-search" aria-hidden="true"></i>
                                </button>
                            </div>
                        </form>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container pt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Cookbook
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>